// Supabase config
export const SUPABASE_URL = "https://cjbagfragoqhkdwylzgz.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqYmFnZnJhZ29xaGtkd3lsemd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzM5MTAsImV4cCI6MjA4ODI0OTkxMH0.t-QLx1i1xDnA60r8TT7GYCOk5hCxJW0y25MdDh3RSkU";